name: Keep Alive

on:
  schedule:
    - cron: '*/14 * * * *' # Runs every 10 minutes
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: |
          echo "Pinging Render server to keep it alive..."
          curl -I https://vegabackendserver.onrender.com
          echo "Ping complete."
